### ISSUE TITLE
Peer review milestone 4

### ISSUE THREAD

**Issue by mkhambat** [airavata-courses/200-ok#109]
Hi team,
The application looks amazing, great job on making things look perfect! The UI looks amazing as well. However, I just faced one issue while using Google sign in, but apart from that I didn't find any major issues with the architecture or devops tools used.

Regards,
Murtaza Khambaty.

**Comment by maheshbelnekar** [comment]
Thanks for your feedback @mkhambat. We have kept your google sign in issue open and are actively working on it.

- Mahesh
