### ISSUE TITLE
Flask api: ModuleNotFoundError

### ISSUE THREAD

**Issue by chetan253** [airavata-courses/200-ok#20]
The service works perfectly with command ```python app.py```. You guys need to check with ```python3 app.py``` as mentioned in the documentation and also the corresponding pip3 command.

Error with python3:
$ python3 app.py 
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    from flask_cors import CORS,cross_origin
ModuleNotFoundError: No module named 'flask_cors'

**Comment by shubham1812** [comment]
@chetan253 Please take a pull and try now
