### ISSUE TITLE
Flask-api Mysql versioning error

### ISSUE THREAD

**Issue by tylerthedeveloper** [airavata-courses/200-ok#23]
Not specific Mysql version or dependencies (tried on both mac and windows)

**Comment by tylerthedeveloper** [comment]
Also ran into similar missing applications (mysql client, config parser module)

**Comment by tylerthedeveloper** [comment]
![screen shot 2019-02-06 at 10 41 50 pm](https://user-images.githubusercontent.com/13102536/52425969-19239200-2acb-11e9-87d1-fabb1b25a54a.png)
![screen shot 2019-02-06 at 10 58 14 pm](https://user-images.githubusercontent.com/13102536/52425970-19239200-2acb-11e9-9dca-a6920bbe9120.png)

**Comment by shubham1812** [comment]
@tylerthedeveloper I have looked into it. The code is using flask_mysqld dependency which is a wrapper class made on the official flask-mysql dependency. The problem here is the flask_mysqld installs mysql_client which is not getting installed for some version issue. In the second screenshot, when it is installed it requires dependency from installed mysql on your system which it is not able to found. I will be making some code changes to fix this issue

**Comment by tylerthedeveloper** [comment]
Thanks @shubham1812, let me know and I will be happy to test it

**Comment by vanessapinto257** [comment]
@tylerthedeveloper  @uteerna The fixed code has been updated on git and the wiki has been updated. Please take a pull from release-1.0.0 branch.

**Comment by tylerthedeveloper** [comment]
@vanessapinto257 I have progressed through the updated wiki, thank you for all the updates.

There is a bug in the linux subsystem (bash) on windows not allowing installation and use of virtual env, please see below.


![no-bash-venv](https://user-images.githubusercontent.com/13102536/52536133-71a19c00-2d24-11e9-9d76-393ab0e082ac.PNG)

HOWEVER, the work around is to switch to powershell which relies on directly on the file-system and can correctly match the path.

**Comment by tylerthedeveloper** [comment]
Correction, wiki is not fully complete. @shubham1812 @vanessapinto257 please see this link to address how to activate a virtual env on windows as that is omitted from your wiki:

https://mothergeo-py.readthedocs.io/en/latest/development/how-to/venv-win.html

**Comment by maheshbelnekar** [comment]
Updated wiki, moving issue to milestone 2.0.0 for future enhancements.
