### ISSUE TITLE
Update wiki for maven and flask installation

### ISSUE THREAD

**Issue by uteerna** [airavata-courses/200-ok#24]
Wiki does not have complete steps in case someone is not familiar with maven. The wiki needs to be updated for that. Also, I have a similar flask issue like Tyler has raised. I have a Mac machine and it is not working on it even though the instructions on wiki say that MacOS is a preferred OS. Please look into that.

**Comment by maheshbelnekar** [comment]
Thanks Uteerna,

I have updated wiki with some links to the guides on downloading and installing Maven. Can you please review and let me know if those are good enough or further details are required.

**Comment by maheshbelnekar** [comment]
@uteerna we have fixed the mysql and python error in #23 and will continue to track it in the same thread; can we close this issue?

**Comment by uteerna** [comment]
This looks good. Thanks.
