### ISSUE TITLE
Unable to add a parking garage 

### ISSUE THREAD

**Issue by uteerna** [airavata-courses/200-ok#28]
Hi Team, 

When i add a parking garage to the system it doesn't result in an error but it never creates an entry in the database. I am unable to see my entry in the Overview. Also, in the reserving the parking space every parking space is displaying as Not available. I am not sure if it is because of the total spaces being full or something else. Can you please check this?

Thanks :)

**Comment by maheshbelnekar** [comment]
@uteerna We found the root cause. This issue occurs because of some new validation that we added to the form. Looks like the request never reaches the server.
We are working on it. Thanks.

**Comment by shubham1812** [comment]
@uteerna  Please take a pull now and try! You should be able to add a parking garage.

**Comment by uteerna** [comment]
@shubham1812 I am able to add the garage now. Thanks :)
