### ISSUE TITLE
General suggestions for naming conventions

### ISSUE THREAD

**Issue by tylerthedeveloper** [airavata-courses/200-ok#29]
I think you should come together as a group and think about the open-source aspect of this community more when coming with names of projects, services, folder structures, organization, etc. 

Naming things like "flask" or "java" is more for the course milestones and is less descriptive and harder to visualize when debugging and starting up the code.

Not a priority.

Also, given there are extreme difference between windows and mac, it might be helpful to section them off and say "installation on windows" list the steps, then switch to mac, rather then interleaving them, it makes it harder to read

**Comment by tylerthedeveloper** [comment]
I'll add on to the above, see if starting the app can launch the browser and run index.html rather than what is suggested
Lastly, a lot of your stuff in the wiki is under assignment 1, but is still part of the whole project, and that will get ignored in assignment 2, so i would separate them

**Comment by shubham1812** [comment]
Hi Tyler
Thanks for the suggestions. We will definitely be working on this. We will have to change the name and test it if there are any breaking changes. About index.html, as the frontend is not really on a server yet, I am not sure if starting API server will open the browser, but in the future, we will be using Apache server and that will definitely solve the issue.
Also, Thanks for the suggestion we will be changing the wiki soon

**Comment by maheshbelnekar** [comment]
For now, added some generic wiki pages, not limited to any assignment.

Moving to milestone 2.0.0.
