### ISSUE TITLE
Broken redirection

### ISSUE THREAD

**Issue by uteerna** [airavata-courses/200-ok#31]
Hi Team, 

When I am logged in to the website and I click on the PARK MY CAR on the top left. It redirects me to a blank white page. Can you please redirect it to something instead of leaving it blank? In my opinion, it will be a good enhancement.

**Comment by shubham1812** [comment]
@uteerna  the issue is fixed. you can take a new pull and check

**Comment by uteerna** [comment]
@shubham1812 looks good now.
