### ISSUE TITLE
Assignment 1

### ISSUE THREAD

**Issue by nawazkh** [airavata-courses/200-ok#35]
Hey team,

I just started with the code review. Will update my progress/issues here.

Thanks,
Nawaz

**Comment by nawazkh** [comment]
Hey Team,

Great Work! I really liked:
1) Your documentation to install and checkout your code.
2) Project as a whole! Its good! 

Areas of improvement: 
1) If only the user could see number of available spots against total spots for each location, it would be much more smooth.

Keep up the good work!

-Nawaz

**Comment by nawazkh** [comment]
Also, in the documentation do mention which micro-service is built using which programming language.

Please close this comment later.

**Comment by shubham1812** [comment]
Hi Nawaz,
Thanks for your valuable feedback. I am creating an issue for showing the number of spots available at each location.
Also, will update the documentation and mention the programming languages used for each microservice.

**Comment by nawazkh** [comment]
I am closing the issue here.
