### ISSUE TITLE
Peer Review: Milestone 2

### ISSUE THREAD

**Issue by aralshi** [airavata-courses/200-ok#48]
Hi,

I am not able to find instructions to start peer review. Please let me know the Jenkins URL along with username and password.

**Comment by shubham1812** [comment]
Hi @aralshi 
Please go to https://github.com/airavata-courses/200-ok/wiki/Milestone-2
and follow the steps. You don't need user id and password to see the builds.

**Comment by aralshi** [comment]
Hi @shubham1812 

I was able to see the pipelines building on dummy commit and test the application through front end. Can you please let me know where is the Jenkins file?

**Comment by shubham1812** [comment]
Hi @aralshi 
We are not using Jenkins Pipeline as of now. We are mentioning the configurations by command line at the run time

**Comment by aralshi** [comment]
Hi @shubham1812 ,

Without credentials I can't check the job configurations as well.

**Comment by aralshi** [comment]
Peer Review Milestone2:

Great job with all the tasks performed for milestone 2. I was able to run all the pipelines with single dummy commit. UI looks clean and user friendly. Use cases are well defined. I was able to test user cases.

Suggestions:
1. Add test cases to micro services to test the application before deploying.
2. Add details about RabitMQ implementation in Wiki. So that it is easier to understand.
3. add_park_api node application contains node_modules. They should not be committed to git. npm install can install all the node modules at runtime.
4. You can create a pipeline to run the front end as well. Every change in frontend will get directly deployed.
5. Can create Jenkinsfile for pipelines so that anyone can use it deploy the application.

Thank you!

**Comment by maheshbelnekar** [comment]
Thanks @aralshi this are some really great suggestions. We will be actively work on them!
