### ISSUE TITLE
No notification on reserving a spot

### ISSUE THREAD

**Issue by morparia-p** [airavata-courses/200-ok#55]

**Comment by morparia-p** [comment]
Hi  team @airavata-courses/200-ok ,

I was unable to get confirmation of my parking spot booking. Is there a notification/registration for drivers?

**Comment by vanessapinto257** [comment]
Hi @morparia-p,
The confirmation is received on the screen when your reservation has been successful. As of yet, we are not sending a separate confirmation by email.
We will keep that in mind when carrying out future improvements.

**Comment by morparia-p** [comment]
Sounds good @vanessapinto257 ! I'll add a label future work and close the thread.
