### ISSUE TITLE
Connection refused error while adding parking spots

### ISSUE THREAD

**Issue by morparia-p** [airavata-courses/200-ok#56]
Hi team,
I ran into a few errors while adding parking garage.

- I was unable to spot what was wrong with my request to add garage. A validation feedback on UI would be a good idea.

- There was a ERR_CONNECTION_REFUSED error while requesting a garage. Does it have something to do with #46 ?
<img width="1438" alt="screen shot 2019-03-03 at 5 44 58 pm" src="https://user-images.githubusercontent.com/33207301/53703219-75818500-3ddd-11e9-8fe0-e502c86ced56.png">

**Comment by shubham1812** [comment]
Hi @morparia-p ,
The server was down and therefore it was giving that problem. Please try now.

**Comment by morparia-p** [comment]
Hey Team,

Faced a similar issue again. 
<img width="1440" alt="screen shot 2019-03-03 at 7 49 46 pm" src="https://user-images.githubusercontent.com/33207301/53704807-d913ae80-3ded-11e9-9888-b1c3e7bb6c68.png">

**Comment by maheshbelnekar** [comment]
@morparia-p I apologize for that, looks like we are facing issue with permission. I have fixed the issue. Can you please verify it one last time.

**Comment by morparia-p** [comment]
No worries. 
I am facing issue in the following. can you please take a look

1. Choose Location

2. Register Your garage -  login and register user.
