### ISSUE TITLE
Review summary: Milestone 2 (Paritosh)

### ISSUE THREAD

**Issue by morparia-p** [airavata-courses/200-ok#58]
Hi @airavata-courses/200-ok ,
The following is the summary of my review:

- The wiki Architecture diagram and user stories made the project easy to understand. 

- The Wiki page is simple to follow.

- The app UI was simple to use and looked clean. I really liked it.

- The jenkins builds deployed as expected on commit.

- Found a few bugs and suggested some improvements #55 #56 #57 

- 👍 for being active on git hub issues and using the project board.

**Comment by morparia-p** [comment]
Also I would have liked if I could review the jenkins script too, so that if there was something new for me, I could learn. Or could suggest you some changes based on what I know.

**Comment by shubham1812** [comment]
Hi @morparia-p ,
Thanks for the review. I will shortly update you with the jenkins architecure
