### ISSUE TITLE
Assignment 2 grading

### ISSUE THREAD

**Issue by raghu2094** [airavata-courses/200-ok#60]
Hi Team,

Can you mail the credentials for your jenkins server.
Email: rtalwai@iu.edu

Regards,
Raghottam

**Comment by shubham1812** [comment]
Hi @raghu2094,
Your credentials username: raghu2094
password: 200ok123

**Comment by raghu2094** [comment]
@shubham1812 Thanks for providing the credentials. I did a dummy commit on your develop branch but I am not able to see any build getting triggered in Jenkins. Has Jenkins been integrated correctly?

**Comment by shubham1812** [comment]
Hi @raghu2094 ,
Please check now. There was some error with Github apps. Jenkins service was apparently deprecated.

**Comment by raghu2094** [comment]
Hi Team,
I was going through your Jenkins jobs. I can see that you are building and deploying the service on the same instance. Ideally , the build and testing of each service should be on the dev instance(which is the Jenkins instance in your case) and after successful building and testing , each service should be deployed to its respective production instance. This process of building testing and deploying should be continuous which is the essence of CI/CD. 

Regards,
Raghottam

**Comment by shubham1812** [comment]
Hi Raghu,
Each service is deployed on a separate node except the UI, which is on the same instance. We have not done this using pipeline scripts, instead made 3 different nodes for deploying the 3 different services. As per the requirement, Jenkins node makes the build on the Jenkins instance and then scp it to the mentioned node for that build. You can check the flow by clicking on any node.

**Comment by raghu2094** [comment]
@shubham1812  In your case, with the master slave configuration , Whenever a commit is made to a particular service's branch, the Jenkins master node will run the build job on the corresponding slave. So, build, test and deploy will happen on the same instance. Right? 
Also, it would be a good idea to explain your deployment strategy in the WIKI. Currently your WIKI doesn't say much about how CI/CD is acheived.

**Comment by shubham1812** [comment]
Hi @raghu2094 ,
Yes, you are right! I understood the issue now. We have achieved the CI/CD by building and deploying is happening on the slave instance now. We can make a note of this and change it in the next milestone so that testing happens on the Jenkins instance. Also, we will update the wiki.
We can make that change now if you would like to see it now.

**Comment by raghu2094** [comment]
@shubham1812 Update the WIKI and also include some test cases for every service. Every build should be tested before deploying

**Comment by shubham1812** [comment]
Hi @raghu2094 ,
Will do it and update.

**Comment by shubham1812** [comment]
Hi @raghu2094 ,
Please check the wiki now.
https://github.com/airavata-courses/200-ok/wiki/Milestone-2

**Comment by raghu2094** [comment]
@shubham1812 By test cases I mean't writing actual tests scripts for each service and including it in your freestyle jobs.

**Comment by raghu2094** [comment]
*I meant

**Comment by shubham1812** [comment]
@raghu2094 ,
Oh okay! Creating an issue for that. Will do it!
