### ISSUE TITLE
UI-Sessions not working

### ISSUE THREAD

**Issue by thumblas** [airavata-courses/200-ok#78]

**Comment by maheshbelnekar** [comment]
Hey @thumblas, 
The ip address on homepage was stale, website is hosted on http://149.165.169.93

**Comment by maheshbelnekar** [comment]
Hey @thumblas , The focus of this milestone was on making the architecture scalable. UI sessions issue has been planned or next milestone. Thanks for bringing it up.

**Comment by thumblas** [comment]
Hey @maheshbelnekar ,

Alright. Rest seems ok to me
