### ISSUE TITLE
Update the Wiki for Jmeter

### ISSUE THREAD

**Issue by thumblas** [airavata-courses/200-ok#79]
Hey team,
Please update the wiki for Jmeter so that I can test it.

Thanks,
Shivani

**Comment by maheshbelnekar** [comment]
Hey @thumblas, We have updated the [wiki](https://github.com/airavata-courses/200-ok/wiki/Milestone-3).
Thanks.

**Comment by maheshbelnekar** [comment]
@thumblas We have posted the results, how exactly do you want to test it?

**Comment by thumblas** [comment]
Looks Good. The wiki has all the essentials.

Thanks,
Shivani
