### ISSUE TITLE
Peer Review: Milestone 3

### ISSUE THREAD

**Issue by jkumar10** [airavata-courses/200-ok#80]

**Comment by jkumar10** [comment]
Hi Team, for peer evaluation I'll begin with checking your jenkins server, followed by checking individual microservices (docker/kubernetes) whichever applicable and final application. Can someone share jenkins credentials at jaikumar@iu.edu?

**Comment by shubham1812** [comment]
Hi @jkumar10 ,
Please use : 
username: peer-review
password: peerreview
