### ISSUE TITLE
Choose location: Not available on homepage

### ISSUE THREAD

**Issue by jkumar10** [airavata-courses/200-ok#83]
Hello Team, 

In the nearest available parking spot, for all requests I am always getting the output as : Choose location not available (in red) and park my car link doesn't seem to work.

**Comment by shubham1812** [comment]
Hi jkumar,
You need to add more locations in the database. You can check the user stories.
To test, you have to first signup and add a parking garage for the current date.
Then when you are back to the home page, you should be able to see a new location. When you click on it, you will be able to see the number of available spots and will have the option of reserving it

**Comment by jkumar10** [comment]
okay cool! now the garages are getting added however after adding the garages it still shows as not available  in red on the homepage when I click that garage. Is this a known issue or am I doing something wrong? Like you said I am not getting the option for reserving. The green button just disappears! If I am doing something wrong then you can ignore this or fix it in next phase.

One suggestion, you can provide strict error checking on form field "Total number of parking garage". Consider entering negative values. I really liked the way how error checking is done on the calendar which is neat!

**Comment by shubham1812** [comment]
Hi @jkumar10 ,
We have noted the issue you have pointed out and will add it to our next milestone
Thank you!
