### ISSUE TITLE
Update details for docker/Kubernetes container testing

### ISSUE THREAD

**Issue by jkumar10** [airavata-courses/200-ok#87]
Hi Team,
I am not able to check how many containers are deployed via docker/kubernetes via Jenkins. Let me know how to proceed with testing of load balancing and kubernetes/swarm cluster. I can give you my public key via email if you can give me the email id of one of your team-members.

**Comment by maheshbelnekar** [comment]
Hi, 
Send us your public key on sgodshal@iu.edu

**Comment by shubham1812** [comment]
Hi @jkumar10 ,
We have added your RSA key. Please ssh to ubuntu@149.165.171.50 and go to the sudo user to check our cluster.

**Comment by jkumar10** [comment]
okay thanks!
