### ISSUE TITLE
Peer Review Milestone 3

### ISSUE THREAD

**Issue by rohankasture** [airavata-courses/200-ok#90]
Summary of Peer Review:

Findings:
CI/CD pipeline works fine.
The overall application looks good to me.
Focus on UI for the final milestone
Kubernetes and KubMonkey works well

Improvements:
-UI can be improved. As noted in issue #83 strict form checking should be implemented to check for errors and other enhancements can be done.
-JMeter testing looked fine to me but individual service testing is missing.
-User session issue
-Add Garage Form validation

**Comment by maheshbelnekar** [comment]
Hi @rohankasture , Thanks for the review.
Regarding JMeter individual testing, we performed simultaneous service tests as it better imitates real life scenario. Also, it is much severe testing as compared to testing individual services. If the system is able to perform well under simultaneous load it is expected to perform better under individual testing.

**Comment by maheshbelnekar** [comment]
Regarding, UI and form validations, we have planned that for next milestone. This milestone was more concentrated on creating a robust and scalable architecture.
