### ISSUE TITLE
Peer Review Milestone 3

### ISSUE THREAD

**Issue by nawazkh** [airavata-courses/200-ok#93]
Hey Team,
I will be starting with the peer review for milestone3. 
-Nawaz

**Comment by nawazkh** [comment]
Hey team,
Can you please share the master node's IP? 
And please add my public key to the node(ping me on slack, I will send in my public key)? 
I wanted to check kubernetes setup and few other stuff.

**Comment by nawazkh** [comment]
Kubernetes Setup: How are you all accessing the services ? have you configured your system to hit individual services on the pods or have you configured "services" in kubernetes to access a service?? 

Docker containers take a lot of space : Have you tried to use **Alpine** flavor of Java or node or <insert other language> .

JMeter : how are you conducting load testing using JMeter if the services are not being accessed through master IP?

**Comment by maheshbelnekar** [comment]
Hi @nawazkh ,
Below are my comments on some of the points you mentioned. Please let me know if these satisfy our concens.

**Kubernetes Setup:** In our K8s setup each pod can access any other pod in the k8s cluster using IP of any node in the cluster. We are using the masterIP to reach all the pods and services. In our system, both the scenarios take place, we hit individual services and services access other services. All these communication happen using the nodeport. We also have configured loadbalancer which takes care of forwarding requests to individual pods. 

**JMeter :** Yes, all services can be accessed through master IP, and thats how we are performing load testing.

**Comment by shubham1812** [comment]
Hi @nawazkh 
Our images do not take too much space as we have tried to save space by using
openjdk:8-jdk-alpine for java service,
node:8 for node service and 
python:3 for flask service instead of creating ubuntu images for all.
Also, the images are tested and created on different containers so out kubernetes container won't be  using too much processor and space

**Comment by nawazkh** [comment]
_JMeter : Yes, all services can be accessed through master IP, and thats how we are performing load testing._

AFAIK, Openstack does not have a external load balancer. 
Have you installed JMeter on the master VM? or are you testing it from outside? 
If testing it from outside, are you hitting each node's IP to test the functionality?

**Comment by nawazkh** [comment]
Great Work guys! 
I only have few suggestions to make. 
1. Include more test cases to each backend services. 
2. Please describe the choke points of your system. Answer this specific question : when does your system fail. 

Coming to MasterIP:TargetPort, Openstack does support configuring loadbalancer, and the steps to set up a loadbalancer is covered when you setup up the cluster itself. (Do read more on it)
Refer : https://docs.openstack.org/magnum/ocata/dev/kubernetes-load-balancer.html

Keep up the good work! 
-Nawaz
